name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yaml"
      - "upper/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest

    steps:
     - run: pwd && ls -l
     - uses: actions/checkout@v4.2.0
     - run: pwd && ls -l
     - run: go version
     - uses: actions/setup-go@v5.2.0
       with:
         go-version: 1.22
     - run: go version
     - run: |
        ls
        go build
        ls
        go test
        ./upper ABC
       working-directory: upper
